Домашнее задание №1
Enoel-py/2021-1-MAILRU-SDET-Python-E-Arrokho pull request #1
Opened 2021-03-29 15:27 UTC by Enoel-py

# Домашнее задание №1

Прошу @snicks92 или @crisscuola или @adamakalshchikov или @stpn111 проверить его.

Что было сделано:

* Написаy тест на логин

* Написан тест на логаут

* Написан тест на редактирование контактной информации в профиле

* Написан параметризованный тест на переход на страницы портала через кнопки в шапке меню

2021-03-29 20:52 UTC, snicks92 requested changes
В целом все хорошо. Добавить проверок бы и локаторы поправить

2021-03-29 20:52 UTC, snicks92 commented on SDET-Python-homework-1/ui/locators/locators.py
> +    MAIN_LOGIN_LOCATOR = (By.CSS_SELECTOR, 'div.responseHead-module-button-1BMAy4')  # Кнопка "ВОЙТИ"
`-1BMAy4` плохой план, эта часть может измениться в любой момент и тесты сломаются

2021-03-29 20:52 UTC, snicks92 commented on SDET-Python-homework-1/Tests/test1.py
> +    assert main_page.check_element(MainPageLocators.CONTACTS_SAVE_SUCCES)
этого точно достаточно чтобы убедиться, что поля заполнились верно? я бы сделал рефреш страницы и проверил что значения соответствуют тому, что мы заполнили

2021-04-19 10:52 UTC, stpn111 commented
Правок нет, 0 баллов, PR закрыт.

2021-04-19 10:52 UTC, closed without merging